// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akwdkurznlswhplkqtps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrd2RrdXJ6bmxzd2hwbGtxdHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MTA4MDIsImV4cCI6MjA1NjA4NjgwMn0.iR7boBH24cONY_A8Zk2iqDxZFaxWrOpX1eFnIYWw1G8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);